---
- hosts: ng.hr

  vars_files:
    - ng2_vars.yml

  roles:
    - role: geerlingguy.nodejs
      become: yes

  tasks:
    - name: download Yarn repo
      sudo: yes
      get_url:
        url: https://dl.yarnpkg.com/rpm/yarn.repo
        dest: /etc/yum.repos.d/yarn.repo

    - name: install the latest version of Yarn
      sudo: yes
      yum:
        name: yarn
        state: latest

    - name: install angular cli
      sudo: yes
      npm:
          name: angular-cli
          global: yes
